name: Deployment2
on: push   #thrigger when push and manually
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci  #or npm install, ci makes sure that install exact same versions as in development
      - name: Lint
        run: npm run lint       
  test:
    # needs: lint   #runs not parallel but when test ist ready
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  deploy:
    # needs: test   #runs not parallel but when test ist ready
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build 
      - name: Deploy
        run: echo "Deploying..."